# Pre-commit settings / QA
# Author: Angel Martinez-Tenor, 2025. Adapted from https://github.com/angelmtenor/ds-template
# Update hooks: `uv run pre-commit autoupdate`

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-toml
      - id: check-yaml
        exclude: ^helm_config/.*
      - id: check-json
        exclude: (^|/)\.vscode/|^helm_config/
      - id: pretty-format-json
        exclude: ^(.vscode/(settings|extensions)\.json|helm_config/.*)
        args: [--autofix, --no-sort-keys]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: ["--maxkb=2000"]

  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff Check
        entry: uv run ruff check --fix
        language: system
        types: [python]

      - id: ruff-format
        name: Ruff Format
        entry: uv run ruff format
        language: system
        types: [python]

      - id: pyrefly-check
        name: Pyrefly (type checking)
        entry: uv run pyrefly check src
        language: system
        pass_filenames: false

  - repo: https://github.com/checkmake/checkmake.git
    rev: v0.3.0
    hooks:
      - id: checkmake
